# Generated by Django 4.1.7 on 2023-02-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('description', models.TextField()),
                ('instructors', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField()),
                ('existing_rating', models.FloatField(default=0)),
                ('user_rating', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
